'use strict';

module.exports = {
	extends: 'stylelint-config-standard',
	plugins: [
		'stylelint-order'
	],
	rules: {
		// Overwritten rules
		'block-no-empty': null,
		'comment-empty-line-before': null,
		'indentation': null,
		'rule-empty-line-before': null,

		// Added rules
		'color-named': 'never',
		'font-family-name-quotes': 'always-where-recommended',
		'font-weight-notation': 'named-where-possible',
		'function-blacklist': ['rgb'],
		'function-url-quotes': 'never',
		'string-quotes': 'single',

		'order/order': [
			'custom-properties',
			'declarations',
			'rules'
		],

		'order/properties-order': [
			'width',
			'min-width',
			'max-width',
			'height',
			'min-height',
			'max-height',
			'background',
			'background-color',
			'background-image',
			'background-repeat',
			'background-attachment',
			'background-position',
			'background-position-x',
			'background-position-y',
			'background-clip',
			'background-origin',
			'background-size',
			'box-decoration-break',
			'font',
			'font-family',
			'src',
			'font-size',
			'font-weight',
			'font-style',
			'font-variant',
			'font-size-adjust',
			'font-stretch',
			'font-effect',
			'font-emphasize',
			'font-emphasize-position',
			'font-emphasize-style',
			'font-smooth',
			'-webkit-font-smoothing',
			'-moz-osx-font-smoothing',
			'line-height',
			'color',
			'text-align',
			'text-align-last',
			'vertical-align',
			'white-space',
			'text-decoration',
			'text-emphasis',
			'text-emphasis-color',
			'text-emphasis-style',
			'text-emphasis-position',
			'text-indent',
			'text-justify',
			'letter-spacing',
			'word-spacing',
			'text-outline',
			'text-transform',
			'text-wrap',
			'text-overflow',
			'text-overflow-ellipsis',
			'text-overflow-mode',
			'word-wrap',
			'word-break',
			'text-shadow',
			'tab-size',
			'hyphens',
			'content',
			'quotes',
			'counter-reset',
			'counter-increment',
			'table-layout',
			'empty-cells',
			'caption-side',
			'border-spacing',
			'border-collapse',
			'list-style',
			'list-style-position',
			'list-style-type',
			'list-style-image',
			'display',
			'visibility',
			'float',
			'clear',
			'overflow',
			'overflow-x',
			'overflow-y',
			'clip',
			'flex-direction',
			'flex-order',
			'flex-pack',
			'flex-align',
			'box-sizing',
			'position',
			'top',
			'right',
			'bottom',
			'left',
			'z-index',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			'margin',
			'margin-top',
			'margin-right',
			'margin-bottom',
			'margin-left',
			'border',
			'border-width',
			'border-style',
			'border-color',
			'border-top',
			'border-top-width',
			'border-top-style',
			'border-top-color',
			'border-right',
			'border-right-width',
			'border-right-style',
			'border-right-color',
			'border-bottom',
			'border-bottom-width',
			'border-bottom-style',
			'border-bottom-color',
			'border-left',
			'border-left-width',
			'border-left-style',
			'border-left-color',
			'border-radius',
			'border-top-left-radius',
			'border-top-right-radius',
			'border-bottom-right-radius',
			'border-bottom-left-radius',
			'border-image',
			'border-image-source',
			'border-image-slice',
			'border-image-width',
			'border-image-outset',
			'border-image-repeat',
			'outline',
			'outline-width',
			'outline-style',
			'outline-color',
			'outline-offset',
			'opacity',
			'box-shadow',
			'resize',
			'cursor',
			'pointer-events',
			'transition',
			'transition-delay',
			'transition-timing-function',
			'transition-duration',
			'transition-property',
			'transform',
			'transform-origin',
			'animation',
			'animation-name',
			'animation-duration',
			'animation-play-state',
			'animation-timing-function',
			'animation-delay',
			'animation-iteration-count',
			'animation-direction',
			'user-select',
			'nav-index',
			'nav-up',
			'nav-right',
			'nav-down',
			'nav-left'
		]
	}
};
